global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'client'
    static_configs:
      - targets: ['client:8080']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'order'
    static_configs:
      - targets: ['order:3012']
  - job_name: 'bff'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bff:8000' ]
        labels:
          application: 'BFF - Paye ton kawa'
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product:8080']