global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'clients'
    static_configs:
      - targets: ['clients:3013']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'orders'
    static_configs:
      - targets: ['host.docker.internal:3012']
