global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'client'
    static_configs:
      - targets: ['client:3034']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'order'
    static_configs:
      - targets: ['host.docker.internal:3012']
