name: Build & Push DockerHub

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract version from branch name
        id: extract_tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/release/}
          VERSION="${BRANCH_NAME#release/}"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: antoineletailleur
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64
      #     load: true
      #     tags: |
      #       antoineletailleur/epsi4a-mspr4-msclient:latest
      #       antoineletailleur/epsi4a-mspr4-msclient:${{ steps.extract_tag.outputs.tag }}

      - name: Build and push Docker image simple
        run: |
          docker build -t antoineletailleur/epsi4a-mspr4-msclient:${{ steps.extract_tag.outputs.tag }} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u antoineletailleur --password-stdin
          docker push antoineletailleur/epsi4a-mspr4-msclient:${{ steps.extract_tag.outputs.tag }}

