name: Trigger Terraform CD

on:
  push:
    branches:
      - main

jobs:
  trigger-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Terraform workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.repos.createWorkflowDispatch({
              owner: 'mspr4-msclient',
              repo: 'epsi4a-mspr4-terraform',
              workflow_id: 'terraform.yml',
              ref: 'main'
            })
