name: Trigger Terraform CD

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag from PR branch name
        id: extract_tag
        run: |
          echo "PR_BRANCH=${{ github.head_ref }}"
          TAG=${{ github.head_ref }}
          if [[ "$TAG" == release/* ]]; then
            TAG="${TAG#release/}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Trigger Terraform workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const response = await fetch('https://api.github.com/repos/mspr4-msclient/epsi4a-mspr4-terraform/actions/workflows/terraform.yml/dispatches', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}`,
                'Accept': 'application/vnd.github+json',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                ref: 'main',
                inputs: {
                  image_tag: '${{ steps.extract_tag.outputs.tag }}'
                }
              })
            });

            if (!response.ok) {
              const errorBody = await response.text();
              throw new Error(`GitHub API error: ${response.status} - ${errorBody}`);
            }
